# Generated by Django 3.1.3 on 2020-12-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=100),
        ),
    ]
