# Generated by Django 3.1.3 on 2020-12-03 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201202_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.comment'),
        ),
    ]
