# Generated by Django 3.1.3 on 2020-12-04 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201203_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctions'),
        ),
    ]
