# Generated by Django 3.1.3 on 2020-12-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201211_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.CharField(blank=True, default='No category', max_length=100, null=True),
        ),
    ]
